# Generated by Django 6.0.4 on 2026-05-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('theater', 'Theater'), ('tv', 'TV/Streaming')], max_length=20)),
                ('image_src', models.CharField(max_length=200)),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('anchor_url', models.CharField(max_length=200)),
                ('movie_genre', models.CharField(max_length=30)),
                ('movie_title', models.CharField(max_length=100)),
                ('lower_rating', models.CharField(max_length=5)),
                ('upper_rating', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='MovieTheater',
        ),
        migrations.DeleteModel(
            name='MovieTV',
        ),
    ]
