# Generated by Django 6.0.4 on 2026-05-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie_delete_movietheater_delete_movietv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='anchor_url',
            field=models.CharField(blank=True, default='Unknown', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_genre',
            field=models.CharField(blank=True, default='Unknown', max_length=30, null=True),
        ),
    ]
